### ISSUE TITLE
Add a toplevel README.md file

### ISSUE THREAD

**Issue by felipesanches** [Simple-BR/Br-Print3D#5]
Containing the overall project description. GitHub renders that file in the main repository page, so it is a very good place to put some basic instructions for the users and potential new contributors.

**Comment by lays147** [comment]
Hi Felipe,
Others branchs on this project already have a Readme.md file. 
I ask you to be patient because this project is very new and I'm having to make major changes to it. Much of the project'm still learning, as well as the necessary files on GitHub so that the user can compile and use the BR-Print3D.
